import { Account, Category, Transaction } from './types';

// Full accounts data
export const fullAccountsData: Account[] = [
  {
    account_id: 1,
    account_name: 'Main Checking',
    account_type: {
      type_name: 'checking',
      description: 'Primary checking account',
      is_asset: true,
    },
    account_number: '****1234',
    institution_name: 'Chase Bank',
    currency_code: 'USD',
    initial_balance: 1000.00,
    current_balance: 2345.67,
    is_closed: false,
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2025-11-14T15:30:00Z',
  },
  {
    account_id: 2,
    account_name: 'Emergency Fund',
    account_type: {
      type_name: 'savings',
      description: 'High-yield savings account',
      is_asset: true,
    },
    account_number: '****5678',
    institution_name: 'Chase Bank',
    currency_code: 'USD',
    initial_balance: 3000.00,
    current_balance: 5000.00,
    is_closed: false,
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2025-11-14T15:30:00Z',
  },
  {
    account_id: 3,
    account_name: 'Travel Rewards',
    account_type: {
      type_name: 'credit_card',
      description: 'Credit card account',
      is_asset: false,
    },
    account_number: '****9012',
    institution_name: 'American Express',
    currency_code: 'USD',
    initial_balance: 0,
    current_balance: -890.44,
    credit_limit: 10000,
    is_closed: false,
    created_at: '2024-02-01T10:00:00Z',
    updated_at: '2025-11-14T15:30:00Z',
  },
  {
    account_id: 4,
    account_name: 'Wallet',
    account_type: {
      type_name: 'cash',
      description: 'Physical cash',
      is_asset: true,
    },
    currency_code: 'USD',
    initial_balance: 100.00,
    current_balance: 200.00,
    is_closed: false,
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2025-11-14T15:30:00Z',
  },
  {
    account_id: 5,
    account_name: 'Investment Account',
    account_type: {
      type_name: 'investment',
      description: 'Brokerage account',
      is_asset: true,
    },
    account_number: '****3456',
    institution_name: 'Fidelity',
    currency_code: 'USD',
    initial_balance: 5000.00,
    current_balance: 12500.00,
    is_closed: false,
    created_at: '2024-03-01T10:00:00Z',
    updated_at: '2025-11-14T15:30:00Z',
  },
];

// Full categories data
export const fullCategoriesData: Category[] = [
  {
    category_id: 1,
    category_group: 'Food & Dining',
    category_name: 'Groceries',
    category_type: 'expense',
    color_code: '#10b981',
    is_active: true,
    created_at: '2024-01-15T10:00:00Z',
  },
  {
    category_id: 2,
    category_group: 'Food & Dining',
    category_name: 'Restaurants',
    category_type: 'expense',
    color_code: '#10b981',
    is_active: true,
    created_at: '2024-01-15T10:00:00Z',
  },
  {
    category_id: 3,
    category_group: 'Transportation',
    category_name: 'Gas & Fuel',
    category_type: 'expense',
    color_code: '#3b82f6',
    is_active: true,
    created_at: '2024-01-15T10:00:00Z',
  },
  {
    category_id: 4,
    category_group: 'Transportation',
    category_name: 'Public Transit',
    category_type: 'expense',
    color_code: '#3b82f6',
    is_active: true,
    created_at: '2024-01-15T10:00:00Z',
  },
  {
    category_id: 5,
    category_group: 'Shopping',
    category_name: 'Online Shopping',
    category_type: 'expense',
    color_code: '#f59e0b',
    is_active: true,
    created_at: '2024-01-15T10:00:00Z',
  },
  {
    category_id: 6,
    category_group: 'Entertainment',
    category_name: 'Streaming Services',
    category_type: 'expense',
    color_code: '#8b5cf6',
    is_active: true,
    created_at: '2024-01-15T10:00:00Z',
  },
  {
    category_id: 7,
    category_group: 'Bills & Utilities',
    category_name: 'Electric',
    category_type: 'expense',
    color_code: '#ef4444',
    is_active: true,
    created_at: '2024-01-15T10:00:00Z',
  },
  {
    category_id: 8,
    category_group: 'Income',
    category_name: 'Salary',
    category_type: 'income',
    color_code: '#059669',
    is_active: true,
    created_at: '2024-01-15T10:00:00Z',
  },
  {
    category_id: 9,
    category_group: 'Income',
    category_name: 'Freelance',
    category_type: 'income',
    color_code: '#059669',
    is_active: true,
    created_at: '2024-01-15T10:00:00Z',
  },
  {
    category_id: 10,
    category_group: 'Transfer',
    category_name: 'Account Transfer',
    category_type: 'transfer',
    color_code: '#6b7280',
    is_active: true,
    created_at: '2024-01-15T10:00:00Z',
  },
];

// Full transactions data
export const fullTransactionsData: Transaction[] = [
  {
    transaction_id: 1,
    account: { account_id: 1, account_name: 'Main Checking' },
    payee: { payee_id: 1, payee_name: 'Acme Corp' },
    category: { category_id: 8, category_name: 'Salary', category_group: 'Income' },
    transaction_type: 'income',
    amount: 3200.00,
    currency_code: 'USD',
    transaction_date: '2025-11-12T00:00:00Z',
    description: 'Monthly salary payment',
    status: 'cleared',
    created_at: '2025-11-12T08:00:00Z',
    updated_at: '2025-11-12T08:00:00Z',
  },
  {
    transaction_id: 2,
    account: { account_id: 1, account_name: 'Main Checking' },
    payee: { payee_id: 2, payee_name: 'Safeway' },
    category: { category_id: 1, category_name: 'Groceries', category_group: 'Food & Dining' },
    transaction_type: 'expense',
    amount: 87.23,
    currency_code: 'USD',
    transaction_date: '2025-11-14T00:00:00Z',
    description: 'Weekly grocery shopping',
    status: 'cleared',
    created_at: '2025-11-14T10:30:00Z',
    updated_at: '2025-11-14T10:30:00Z',
  },
  {
    transaction_id: 3,
    account: { account_id: 3, account_name: 'Travel Rewards' },
    payee: { payee_id: 3, payee_name: 'Shell' },
    category: { category_id: 3, category_name: 'Gas & Fuel', category_group: 'Transportation' },
    transaction_type: 'expense',
    amount: 45.00,
    currency_code: 'USD',
    transaction_date: '2025-11-14T00:00:00Z',
    description: 'Gas station',
    status: 'pending',
    created_at: '2025-11-14T14:15:00Z',
    updated_at: '2025-11-14T14:15:00Z',
  },
  {
    transaction_id: 4,
    account: { account_id: 3, account_name: 'Travel Rewards' },
    payee: { payee_id: 4, payee_name: 'Starbucks' },
    category: { category_id: 2, category_name: 'Restaurants', category_group: 'Food & Dining' },
    transaction_type: 'expense',
    amount: 5.75,
    currency_code: 'USD',
    transaction_date: '2025-11-13T00:00:00Z',
    description: 'Morning coffee',
    status: 'cleared',
    created_at: '2025-11-13T08:45:00Z',
    updated_at: '2025-11-13T08:45:00Z',
  },
  {
    transaction_id: 5,
    account: { account_id: 1, account_name: 'Main Checking' },
    payee: { payee_id: 5, payee_name: 'Amazon' },
    category: { category_id: 5, category_name: 'Online Shopping', category_group: 'Shopping' },
    transaction_type: 'expense',
    amount: 156.99,
    currency_code: 'USD',
    transaction_date: '2025-11-13T00:00:00Z',
    description: 'Home office supplies',
    status: 'cleared',
    created_at: '2025-11-13T16:20:00Z',
    updated_at: '2025-11-13T16:20:00Z',
  },
  {
    transaction_id: 6,
    account: { account_id: 1, account_name: 'Main Checking' },
    payee: { payee_id: 6, payee_name: 'Target' },
    category: { category_id: 1, category_name: 'Groceries', category_group: 'Food & Dining' },
    transaction_type: 'expense',
    amount: 43.21,
    currency_code: 'USD',
    transaction_date: '2025-11-11T00:00:00Z',
    description: 'Household items',
    status: 'cleared',
    created_at: '2025-11-11T19:10:00Z',
    updated_at: '2025-11-11T19:10:00Z',
  },
  {
    transaction_id: 7,
    account: { account_id: 3, account_name: 'Travel Rewards' },
    payee: { payee_id: 7, payee_name: 'Chipotle' },
    category: { category_id: 2, category_name: 'Restaurants', category_group: 'Food & Dining' },
    transaction_type: 'expense',
    amount: 12.50,
    currency_code: 'USD',
    transaction_date: '2025-11-10T00:00:00Z',
    description: 'Lunch',
    status: 'reconciled',
    created_at: '2025-11-10T12:30:00Z',
    updated_at: '2025-11-10T12:30:00Z',
  },
  {
    transaction_id: 8,
    account: { account_id: 1, account_name: 'Main Checking' },
    payee: { payee_id: 8, payee_name: 'Uber' },
    category: { category_id: 4, category_name: 'Public Transit', category_group: 'Transportation' },
    transaction_type: 'expense',
    amount: 23.45,
    currency_code: 'USD',
    transaction_date: '2025-11-09T00:00:00Z',
    description: 'Ride to airport',
    status: 'cleared',
    created_at: '2025-11-09T07:15:00Z',
    updated_at: '2025-11-09T07:15:00Z',
  },
  {
    transaction_id: 9,
    account: { account_id: 1, account_name: 'Main Checking' },
    payee: { payee_id: 9, payee_name: 'Netflix' },
    category: { category_id: 6, category_name: 'Streaming Services', category_group: 'Entertainment' },
    transaction_type: 'expense',
    amount: 15.99,
    currency_code: 'USD',
    transaction_date: '2025-11-08T00:00:00Z',
    description: 'Monthly subscription',
    status: 'cleared',
    created_at: '2025-11-08T00:01:00Z',
    updated_at: '2025-11-08T00:01:00Z',
  },
  {
    transaction_id: 10,
    account: { account_id: 3, account_name: 'Travel Rewards' },
    payee: { payee_id: 3, payee_name: 'Shell' },
    category: { category_id: 3, category_name: 'Gas & Fuel', category_group: 'Transportation' },
    transaction_type: 'expense',
    amount: 52.00,
    currency_code: 'USD',
    transaction_date: '2025-11-07T00:00:00Z',
    description: 'Gas station',
    status: 'cleared',
    created_at: '2025-11-07T17:45:00Z',
    updated_at: '2025-11-07T17:45:00Z',
  },
];
